# Site settings
title: Will's blog on github
email: wware@alum.mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Will Ware's random thoughts, mostly about coding stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wware.github.io" # the base hostname & protocol for your site
twitter_username: wware
github_username:  wware

# Build settings
markdown: kramdown
