site_name: Will Ware
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
  features:
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

plugins:
  - search
  - mermaid2

#extra:
#analytics:
#    provider: google
#property: G-XXXXXXXXXX  # Replace with your Google Analytics 4 property ID
